import type { Metadata } from "next";


export const metadata: Metadata = {
    title: {
        default: "Create Next App",
        template: "%s | resume"
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className=''>
                <menu>menu</menu>
                {children}
            </body>
        </html>
    );
}
