"use client"
import { motion } from "framer-motion";
import type { Metadata } from "next";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";


export const metadata: Metadata = {
    title: {
        default: "Create Next App",
        template: "%s | resume"
    },
    description: "Generated by create next app",
};

const links = [

    {
        name: 'experience',
        path: '/experience'
    },
    {
        name: 'education',
        path: '/education'
    },
    {
        name: 'skills',
        path: '/skills'
    },
    {
        name: 'about me',
        path: '/aboutme'
    }

]

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname()

    return (
        <div className="flex flex-col justify-between items-start w-full lg:flex-row ">
            <div className="flex flex-col lg:w-[35%] mt-16 lg:ml-16">
                <motion.div
                    initial={{ opacity: 0, x: -100 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.5, }}
                    className="flex flex-col gap-4 mt-16 lg:ml-4 mx-4"
                >
                    <div className="inika-bold text-lg lg:text-xl flex gap-2">
                        My <div className="text-green">resume</div>
                    </div>
                    <div className="w-[20rem]">
                        <div className="inika-bold text-2xl lg:text-5xl text-nowrap">Why hire me?</div>
                        <div className="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </div>
                    </div>
                </motion.div>
                <div className="w-[20rem] mx-4 mt-4 mb-8 flex flex-col gap-2">
                    {links.map((link,index) => {
                        const isActive = pathname.startsWith(`/resume${link.path}`);
                        const delay = 0.5
                        return (
                            <Link href={`/resume/${link.path.slice(1)}`} key={link.name} className=" hover:opacity-80 transition-all duration-200">
                                <motion.div
                                    initial={{ opacity: 0, y: 50 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ duration: 0.5, delay: (0.25 + index)/2 }}
                                    className={` ${isActive == true ? 'bg-green text-dark-gray' : 'bg-light-gray'} w-full py-2 inika-regular  rounded-md text-center  capitalize`}
                            >
                                {link.name}
                            </motion.div>
                            </Link>                        
                            )
                    })}
                </div>
            </div>
            {children}
        </div>
    );
}
